<!DOCTYPE html>

<head>
    <title>Manejo de errores</title>
</head>

<body>
    <script>
        //ASYNC/AWAIT
        async function sumarNumeros(a, b) {
            if (typeof a != 'number' || typeof b != 'number') {
                throw new Error('alguno de los argumentos no es numero');
            }
            return a + b
            
        }

        async function manejarErrores() {
            try{
                let resultado = await sumarNumeros('2', 3);
                console.log(resultado);
            } catch (error) {
                console.error(error.message);
            }
            
        }

        manejarErrores();
    </script>
</body>